### ISSUE TITLE
Expected behavior of user cancelling a reboot?

### ISSUE THREAD

**Issue by dleviminzi** [risoflora/system_shutdown#12]
Hello, while using this project I noticed that when using the `reboot()` method a user cancellation would not work. I am using gnome, so I can't speak to what happens in other environments. 

Anyway, in gnome using `reboot()` will prompt the user via ui with the options to cancel or reboot. I would expect the user pressing cancel to stop the reboot from happening. However, [these lines](https://github.com/risoflora/system_shutdown/blob/main/src/linux.rs#L268-L269) cause the system to reboot even if the user cancels. I am not sure if this was acknowledged and agreed upon as the expected behavior, but I found it odd and thought I would mention it. 

I was thinking that perhaps it could be handled like this: 
```
match reply {
    Err(Some(x)) if x == "Operation was canceled" => true,
    _ => reply.is_ok(),
}
```
This also feels a bit strange though because the cancellation message depends on what environment you're in

**Comment by silvioprog** [comment]
cc @AdrianEddy

**Comment by silvioprog** [comment]
(cc @AdrianEddy)

**Comment by AdrianEddy** [comment]
Good catch, this is indeed a bug and cancelling a reboot should not execute these lines. I'll try to fix it this week
