### ISSUE TITLE
Sleep

### ISSUE THREAD

**Issue by WilliamVenner** [risoflora/system_shutdown#6]
Would be nice if we could put the computer to sleep too 😴

**Comment by AdrianEddy** [comment]
There is a `sleep()` function already, although not released to crates.io. You can use github dependency in your Cargo.toml though

@silvioprog can you upload the new version to crates.io?

**Comment by WilliamVenner** [comment]
Oh, nice one :)

**Comment by silvioprog** [comment]
For sure @AdrianEddy! 🙂

**Comment by silvioprog** [comment]
Hey @AdrianEddy, new version published to crates.io: https://crates.io/crates/system_shutdown 🎉 

Also, added you (user `AdrianEddy`, let me know if it is yours) to also handle the [crates.io/system_shutdown](https://crates.io/crates/system_shutdown), so feel free to publish new versions of the library whenever you want! 🙂
